# Generated by Django 4.2.5 on 2023-09-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_todo_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
    ]
